add_test( basic.dstCheck /home/yossarian/PROJECTS/tcp_simulation/test1 [==[--gtest_filter=basic.dstCheck]==] --gtest_also_run_disabled_tests)
set_tests_properties( basic.dstCheck PROPERTIES WORKING_DIRECTORY /home/yossarian/PROJECTS/tcp_simulation SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( basic.send /home/yossarian/PROJECTS/tcp_simulation/test1 [==[--gtest_filter=basic.send]==] --gtest_also_run_disabled_tests)
set_tests_properties( basic.send PROPERTIES WORKING_DIRECTORY /home/yossarian/PROJECTS/tcp_simulation SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( basic.backoff /home/yossarian/PROJECTS/tcp_simulation/test1 [==[--gtest_filter=basic.backoff]==] --gtest_also_run_disabled_tests)
set_tests_properties( basic.backoff PROPERTIES WORKING_DIRECTORY /home/yossarian/PROJECTS/tcp_simulation SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test( basic.duplicate /home/yossarian/PROJECTS/tcp_simulation/test1 [==[--gtest_filter=basic.duplicate]==] --gtest_also_run_disabled_tests)
set_tests_properties( basic.duplicate PROPERTIES WORKING_DIRECTORY /home/yossarian/PROJECTS/tcp_simulation SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set( test1_TESTS basic.dstCheck basic.send basic.backoff basic.duplicate)
